services:
  backend:
    build: ./backend
    container_name: ytvenger
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
